[build]
  cmd = "go run ./cmd"
  include_ext = ["go"]
  exclude_file = ["*_templ.go"]
  exclude_dir = ["vendor", "node_modules", "tmp", "./cmd/static", "./templates/generated"]
  include_dir = ["./cmd/"]
  include_file = ["./data.go", "./cmd/**/*.go"]
  silent = false
