// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GETCounters(arg1) {
  return window['go']['backend']['App']['GETCounters'](arg1);
}

export function GenerateCounters(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GenerateCounters'](arg1, arg2, arg3);
}

export function GetCounters() {
  return window['go']['backend']['App']['GetCounters']();
}

export function GetImage(arg1) {
  return window['go']['backend']['App']['GetImage'](arg1);
}

export function OnEvent(arg1, arg2) {
  return window['go']['backend']['App']['OnEvent'](arg1, arg2);
}

export function SSE(arg1) {
  return window['go']['backend']['App']['SSE'](arg1);
}

export function SelectFile() {
  return window['go']['backend']['App']['SelectFile']();
}

export function Total(arg1) {
  return window['go']['backend']['App']['Total'](arg1);
}

export function Watch(arg1) {
  return window['go']['backend']['App']['Watch'](arg1);
}
