// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fiber} from '../models';
import {context} from '../models';
import {server} from '../models';

export function GETCounters(arg1:fiber.Ctx):Promise<void>;

export function GenerateCounters(arg1:context.Context,arg2:Array<number>,arg3:Array<server.Subscriber>):Promise<server.CounterImages>;

export function GetCounters():Promise<Array<server.CounterImage>>;

export function GetImage(arg1:string):Promise<Array<number>>;

export function OnEvent(arg1:context.Context,arg2:number):Promise<void>;

export function SSE(arg1:fiber.Ctx):Promise<void>;

export function SelectFile():Promise<string>;

export function Total(arg1:number):Promise<void>;

export function Watch(arg1:context.Context):Promise<void>;
